/**
 * Validate that all migrations are properly formatted Drizzle migrations.
 *
 * This script checks for obviously hand-written migrations that would break
 * the migration tracking system.
 *
 * Run this before committing migrations to catch issues early.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Known hand-written migrations that have already been applied
// These are grandfathered in but should NOT be used as examples
const GRANDFATHERED_MIGRATIONS = new Set([
  "0004_lazy_stingray.sql",
  "0005_lucky_maestro.sql",
  "0006_striped_the_anarchist.sql",
  "0018_rename_gitlab_file_sync_state.sql",
  "0019_modern_purple_man.sql",
  "0020_great_shinko_yamashiro.sql",
  "0022_majestic_big_bertha.sql",
]);

function getMigrationFiles(): string[] {
  const migrationsDir = path.join(__dirname, "../src/db/migrations");
  if (!fs.existsSync(migrationsDir)) {
    console.error(`Migrations directory not found: ${migrationsDir}`);
    process.exit(1);
  }

  const files = fs.readdirSync(migrationsDir);
  return files.filter((f) => f.endsWith(".sql") && !f.startsWith("."));
}

function validateMigrationFile(filename: string): {
  valid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  const filePath = path.join(__dirname, "../src/db/migrations", filename);
  const content = fs.readFileSync(filePath, "utf-8");

  // Check if file is empty
  if (!content.trim()) {
    errors.push("Migration file is empty");
    return { valid: false, errors, warnings };
  }

  // Check for obviously hand-written migrations
  const hasBreakpoints = content.includes("--> statement-breakpoint");
  const lineCount = content.split("\n").length;

  // Flag files that look like manual SQL edits
  // Specifically: short files with DDL statements but no Drizzle markers
  if (lineCount < 5 && !hasBreakpoints) {
    const hasDDL = /DROP TABLE|ALTER TABLE|CREATE TABLE|CREATE INDEX/i.test(
      content
    );
    if (hasDDL) {
      const isGrandfathered = GRANDFATHERED_MIGRATIONS.has(filename);

      if (isGrandfathered) {
        warnings.push(
          `This is a grandfathered hand-written migration. ` +
            `DO NOT use this as an example. ` +
            `All new migrations MUST be generated via 'pnpm db:generate'.`
        );
      } else {
        errors.push(
          `Migration appears to be hand-written. ` +
            `This file is too short and lacks Drizzle's statement-breakpoint markers. ` +
            `REGENERATE using 'pnpm db:generate' from schema changes. ` +
            `DO NOT edit migration files directly.`
        );
      }
    }
  }

  // Additional check: DROP TABLE without proper structure is suspicious
  // Only warn if we didn't already error on this file
  if (
    /^DROP TABLE/m.test(content.trim()) &&
    !hasBreakpoints &&
    errors.length === 0
  ) {
    const isGrandfathered = GRANDFATHERED_MIGRATIONS.has(filename);

    if (!isGrandfathered) {
      warnings.push(
        `DROP TABLE statement without statement-breakpoint markers. ` +
          `This should typically be generated by Drizzle, not hand-written.`
      );
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

function main() {
  console.log("🔍 Validating Drizzle migrations...\n");

  const migrationFiles = getMigrationFiles();
  console.log(`Found ${migrationFiles.length} migration files\n`);

  let errorCount = 0;
  let warningCount = 0;

  for (const file of migrationFiles) {
    const result = validateMigrationFile(file);

    if (!result.valid) {
      console.error(`❌ ${file}`);
      result.errors.forEach((err) => console.error(`   ERROR: ${err}`));
      errorCount++;
    } else if (result.warnings.length > 0) {
      console.warn(`⚠️  ${file}`);
      result.warnings.forEach((warn) => console.warn(`   WARNING: ${warn}`));
      warningCount++;
    } else {
      console.log(`✅ ${file}`);
    }
  }

  console.log("");

  if (errorCount > 0) {
    console.error(
      `\n❌ Migration validation failed with ${errorCount} error(s)\n`
    );
    console.error("CRITICAL: Never create or edit migration files manually.");
    console.error("Always use 'pnpm db:generate' from schema changes.\n");
    process.exit(1);
  }

  if (warningCount > 0) {
    console.warn(`\n⚠️  Found ${warningCount} warning(s)\n`);
    console.warn("Some migrations are hand-written (grandfathered in). ");
    console.warn("DO NOT use these as examples. ");
    console.warn("Always use 'pnpm db:generate' for new migrations.\n");
    // Don't exit with error for grandfathered migrations
  }

  if (warningCount === 0) {
    console.log("✅ All migrations validated!\n");
  }

  process.exit(0);
}

main();
