/**
 * Character Linker Service — applySpeakerUpdates UUID Cast
 *
 * Regression test for the ::uuid cast on speakerId values in the
 * batch UPDATE generated by applySpeakerUpdates. Without the cast,
 * PostgreSQL rejects the query with:
 *   column "speaker_id" is of type uuid but expression is of type text
 *
 * Drizzle binds JS strings as `text` params, and a CASE expression
 * mixing uuid-looking text with null is inferred as text, so every
 * THEN value must use ::uuid to match the uuid column type.
 */

import { describe, it, expect, vi } from "vitest";
import { characterLinkerService } from "../character-linker.service.js";
import { labelLines } from "../../db/schema/index.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Walk a Drizzle SQL tree and produce the SQL text it represents.
 * Handles SQL (with queryChunks), StringChunk (with value[]), plain
 * strings (inline params), and null (bound NULL literal).
 */
function extractSqlText(chunks: unknown[]): string {
  const parts: string[] = [];
  for (const c of chunks) {
    if (c === null || c === undefined) {
      parts.push("NULL");
    } else if (typeof c === "string") {
      parts.push(c);
    } else if (typeof c === "object") {
      // StringChunk – has a `value` array property of strings
      if (
        "constructor" in c &&
        c.constructor.name === "StringChunk" &&
        "value" in c &&
        Array.isArray(c.value)
      ) {
        parts.push(c.value.join(""));
      } else if ("queryChunks" in c && Array.isArray(c.queryChunks)) {
        // Nested SQL – has queryChunks
        parts.push(extractSqlText(c.queryChunks));
      }
    }
  }
  return parts.join("");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("CharacterLinkerService.applySpeakerUpdates", () => {
  /**
   * Verifies that every THEN branch in the CASE expression includes
   * a ::uuid cast, regardless of whether the speakerId is a UUID
   * string or null.  If the cast is removed, Postgres raises:
   *   column "speaker_id" is of type uuid but expression is of type text
   */
  it("includes ::uuid cast on each THEN value to prevent Postgres uuid vs text error", async () => {
    // Arrange – mock db chain
    const mockWhere = vi.fn<() => Promise<void>>(() => Promise.resolve());
    const mockSet = vi.fn(() => ({ where: mockWhere }));
    const mockUpdate = vi.fn(() => ({ set: mockSet }));
    const mockDb = { update: mockUpdate };

    // Mixed UUID strings and null – exactly what linkSpeakersToLines
    // builds when some lines have a matched character and others don't.
    const updates: Array<{ lineId: string; speakerId: string | null }> = [
      {
        lineId: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
        speakerId: "b1f2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
      },
      { lineId: "c7d8e9f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f", speakerId: null },
      {
        lineId: "e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b",
        speakerId: "f0e1d2c3-b4a5-6c7d-8e9f-0a1b2c3d4e5f",
      },
    ];

    // Act – call the private method via unchecked cast (the method is
    // private on CharacterLinkerService, exposed only for this test)
    const svc = characterLinkerService as unknown as {
      applySpeakerUpdates: (
        updates: Array<{ lineId: string; speakerId: string | null }>,
        db: typeof mockDb
      ) => Promise<void>;
    };
    await svc.applySpeakerUpdates(updates, mockDb);

    // Assert – update was called with the correct table
    expect(mockUpdate).toHaveBeenCalledWith(labelLines);

    // Assert – the first (only) chunk used set()
    expect(mockSet).toHaveBeenCalledTimes(1);

    // Inspect the SQL passed to set()
    const setArg: Record<string, unknown> = mockSet.mock.calls[0][0];
    expect(setArg).toHaveProperty("speakerId");

    const speakerIdSql = setArg.speakerId;
    expect(speakerIdSql).toHaveProperty("queryChunks");

    // Narrow the type with `in` to access queryChunks
    if (
      !speakerIdSql ||
      typeof speakerIdSql !== "object" ||
      !("queryChunks" in speakerIdSql) ||
      !Array.isArray(speakerIdSql.queryChunks)
    ) {
      throw new Error("speakerId is not a Drizzle SQL object");
    }
    const sqlText = extractSqlText(speakerIdSql.queryChunks);

    // Every THEN value carries ::uuid
    expect(sqlText).toContain("::uuid");

    // There should be THREE THEN branches (one per update), each with ::uuid
    const thenMatches = sqlText.match(/THEN\s+\S+::uuid/g);
    expect(thenMatches).toHaveLength(3);

    // Re-assert: the third update was a null, so one of the THENs has
    // NULL::uuid – confirm the cast is there even for null values
    expect(sqlText).toContain("NULL::uuid");

    // Assert – where() was called (the query was executed)
    expect(mockWhere).toHaveBeenCalledTimes(1);
  });
});
