/**
 * RPY Generator Service Tests
 *
 * Unit tests for Ren'Py .rpy file generator.
 */

import { describe, it, expect } from "vitest";
import {
  generateCharacterDefinitionsFile,
  generateConditionCode,
} from "../rpy-generator.service.js";

describe("RPYGeneratorService", () => {
  describe("generateCharacterDefinitionsFile", () => {
    it("should return only the header with a trailing newline for empty characters array", () => {
      const result = generateCharacterDefinitionsFile([]);

      const expectedHeader = `##############################################################################
# Ren'Py Character Definitions
#
# This file was automatically generated by BranchForge
# Modifications may be overwritten during future exports
##############################################################################
`;

      expect(result).toBe(expectedHeader);
      expect(result.endsWith("\n")).toBe(true);
    });

    it("should generate correct define statement for single character", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "Eileen",
          nameType: "literal",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain("# Ren'Py Character Definitions");
      expect(result).toContain("define e = Character");
    });

    it("should generate one define per character in order for multiple characters", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "Eileen",
          nameType: "literal",
          color: "#c8ffc8",
        },
        {
          renpyTag: "s",
          name: "Sylvie",
          nameType: "literal",
          color: "#ff0000",
        },
        {
          renpyTag: "l",
          name: "Lucy",
          nameType: "literal",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain(
        `define s = Character("Sylvie", color="#ff0000")`
      );
      expect(result).toContain(`define l = Character("Lucy", color="#0000ff")`);

      // Check order: e should appear before s, s should appear before l
      const eIndex = result.indexOf('define e = Character("Eileen"');
      const sIndex = result.indexOf('define s = Character("Sylvie"');
      const lIndex = result.indexOf('define l = Character("Lucy"');

      expect(eIndex).toBeLessThan(sIndex);
      expect(sIndex).toBeLessThan(lIndex);
    });

    it('should escape double quotes in display name (e.g. Eileen "The Bold" → Eileen \\"The Bold\\")', () => {
      const characters = [
        {
          renpyTag: "e",
          name: 'Eileen "The Bold"',
          nameType: "literal",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("Eileen \\"The Bold\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Eileen "The Bold"');
    });

    it("should escape backslash in display name (e.g. C:\\Path → C:\\\\Path)", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "C:\\Path",
          nameType: "literal",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("C:\\\\Path", color="#c8ffc8")'
      );
      expect(result).not.toContain("C:\\Path");
    });

    it("should escape both backslash and quote correctly when present together", () => {
      const characters = [
        {
          renpyTag: "e",
          name: 'Path\\To "File"',
          nameType: "literal",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Both should be escaped: \ becomes \\, " becomes \"
      expect(result).toContain(
        'define e = Character("Path\\\\To \\"File\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Path\\To "File"');
    });

    it("should end with a newline when characters array is not empty", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "Eileen",
          nameType: "literal",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Result should end with a newline
      expect(result.endsWith("\n")).toBe(true);
    });

    it("should append what_italic=True for narrator characters", () => {
      const characters = [
        {
          renpyTag: "n",
          name: "Narrator",
          nameType: "literal",
          color: "#cfcfcf",
          isNarrator: true,
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define n = Character("Narrator", color="#cfcfcf", what_italic=True)'
      );
    });

    it("should NOT append what_italic for non-narrator characters", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "Eileen",
          nameType: "literal",
          color: "#c8ffc8",
          isNarrator: false,
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("Eileen", color="#c8ffc8")'
      );
      expect(result).not.toContain("what_italic");
    });

    it("should NOT append what_italic when isNarrator is omitted", () => {
      const characters = [
        {
          renpyTag: "s",
          name: "Sylvie",
          nameType: "literal",
          color: "#ff0000",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define s = Character("Sylvie", color="#ff0000")'
      );
      expect(result).not.toContain("what_italic");
    });

    it("should skip character with invalid renpyTag (e.g. with spaces or special chars)", () => {
      const characters = [
        {
          renpyTag: "valid_tag",
          name: "Valid",
          nameType: "literal",
          color: "#ffffff",
        },
        {
          renpyTag: "bad tag",
          name: "Bad Tag Character",
          nameType: "literal",
          color: "#ff0000",
        },
        {
          renpyTag: "ok",
          name: "Another Valid",
          nameType: "literal",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Valid characters should be included
      expect(result).toContain("valid_tag");
      expect(result).toContain("ok");
      // Invalid character should be skipped
      expect(result).not.toContain("bad tag");
      expect(result).not.toContain("Bad Tag Character");
    });

    it("should skip character with invalid color that is not a hex color", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "Eileen",
          nameType: "literal",
          color: "#c8ffc8",
        },
        {
          renpyTag: "h",
          name: "Hacker",
          nameType: "literal",
          color: 'red") $ evil = True #',
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Valid character should be included
      expect(result).toContain("define e = Character");
      expect(result).toContain("Eileen");
      // Malicious character should be skipped entirely
      expect(result).not.toContain("Hacker");
      expect(result).not.toContain("evil = True");
      expect(result).not.toContain('color="red');
    });

    it("should skip character with invalid renpyTag that starts with a digit", () => {
      const characters = [
        {
          renpyTag: "1bad",
          name: "StartsWithDigit",
          nameType: "literal",
          color: "#ffffff",
        },
        {
          renpyTag: "ok",
          name: "Valid",
          nameType: "literal",
          color: "#ffffff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).not.toContain("1bad");
      expect(result).toContain("ok");
    });

    it("should accept valid 6-digit hex colors", () => {
      const characters = [
        {
          renpyTag: "a",
          name: "White",
          nameType: "literal",
          color: "#ffffff",
        },
        {
          renpyTag: "b",
          name: "Red",
          nameType: "literal",
          color: "#ff0000",
        },
        {
          renpyTag: "c",
          name: "Blue",
          nameType: "literal",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define a = Character("White", color="#ffffff")'
      );
      expect(result).toContain('define b = Character("Red", color="#ff0000")');
      expect(result).toContain('define c = Character("Blue", color="#0000ff")');
    });

    it("should emit interpolated nameType as quoted Character() arg (not displayName)", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "[first_name]",
          nameType: "interpolated",
          displayName: "John",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Must use name (bracketed) not displayName (John)
      expect(result).toContain(
        'define e = Character("[first_name]", color="#c8ffc8")'
      );
      expect(result).not.toContain("John");
    });

    it("should emit variable nameType as unquoted identifier", () => {
      const characters = [
        {
          renpyTag: "boss",
          name: "boss_name",
          nameType: "variable",
          color: "#ff0000",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define boss = Character(boss_name, color="#ff0000")'
      );
    });

    it("should skip variable nameType when name is not a safe identifier", () => {
      const characters = [
        {
          renpyTag: "e",
          name: "not a valid ident!",
          nameType: "variable",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).not.toContain("define e = Character");
      expect(result).not.toContain("not a valid ident!");
    });

    it("should skip variable nameType when name is null", () => {
      const characters = [
        {
          renpyTag: "e",
          name: null,
          nameType: "variable",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).not.toContain("define e = Character");
    });

    it("should emit tagged nameType as quoted string preserving tags", () => {
      const characters = [
        {
          renpyTag: "stranger",
          name: "{color=#f00}Stranger{/color}",
          nameType: "tagged",
          color: "#ffffff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define stranger = Character("{color=#f00}Stranger{/color}", color="#ffffff")'
      );
    });

    it("should emit none nameType as unquoted None", () => {
      const characters = [
        {
          renpyTag: "n",
          name: null,
          nameType: "none",
          color: "#cfcfcf",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain('define n = Character(None, color="#cfcfcf")');
    });

    it("should emit empty nameType as empty quoted string", () => {
      const characters = [
        {
          renpyTag: "m",
          name: "",
          nameType: "empty",
          color: "#000000",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain('define m = Character("", color="#000000")');
    });

    it("should emit unknown nameType as quoted string", () => {
      const characters = [
        {
          renpyTag: "u",
          name: "???",
          nameType: "unknown",
          color: "#888888",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain('define u = Character("???", color="#888888")');
    });
  });

  describe("generateConditionCode", () => {
    it("generates a guard clause for a stat condition with >=", () => {
      const code = generateConditionCode(
        { stats: { health: { value: 50, operator: ">=" } } },
        1
      );
      expect(code).toEqual(["    if not (health >= 50):", "        return"]);
    });

    it("generates a guard clause for a plain-number stat (legacy)", () => {
      const code = generateConditionCode({ stats: { health: 50 } }, 1);
      // legacy plain numbers default to operator ">="
      expect(code).toEqual(["    if not (health >= 50):", "        return"]);
    });

    it("generates guard clauses for a variable condition (truthy)", () => {
      const code = generateConditionCode(
        { variables: { met_alex: { value: true, operator: "truthy" } } },
        1
      );
      expect(code).toEqual(["    if not (met_alex):", "        return"]);
    });

    it("skips invalid stat names and still generates valid code", () => {
      const code = generateConditionCode(
        { stats: { "123invalid": { value: 50, operator: "==" } } },
        1
      );
      expect(code).toEqual([]);
    });
  });
});
