/**
 * RPY Generator Service Tests
 *
 * Unit tests for Ren'Py .rpy file generator.
 */

import { describe, it, expect } from "vitest";
import { generateCharacterDefinitionsFile } from "../rpy-generator.service.js";

describe("RPYGeneratorService", () => {
  describe("generateCharacterDefinitionsFile", () => {
    it("should return only the header with a trailing newline for empty characters array", () => {
      const result = generateCharacterDefinitionsFile([]);

      const expectedHeader = `##############################################################################
# Ren'Py Character Definitions
#
# This file was automatically generated by BranchForge
# Modifications may be overwritten during future exports
##############################################################################
`;

      expect(result).toBe(expectedHeader);
      expect(result.endsWith("\n")).toBe(true);
    });

    it("should generate correct define statement for single character", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain("# Ren'Py Character Definitions");
      expect(result).toContain("define e = Character");
    });

    it("should generate one define per character in order for multiple characters", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
        {
          renpyTag: "s",
          displayName: "Sylvie",
          color: "#ff0000",
        },
        {
          renpyTag: "l",
          displayName: "Lucy",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain(
        `define s = Character("Sylvie", color="#ff0000")`
      );
      expect(result).toContain(`define l = Character("Lucy", color="#0000ff")`);

      // Check order: e should appear before s, s should appear before l
      const eIndex = result.indexOf('define e = Character("Eileen"');
      const sIndex = result.indexOf('define s = Character("Sylvie"');
      const lIndex = result.indexOf('define l = Character("Lucy"');

      expect(eIndex).toBeLessThan(sIndex);
      expect(sIndex).toBeLessThan(lIndex);
    });

    it('should escape double quotes in display name (e.g. Eileen "The Bold" → Eileen \\"The Bold\\")', () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: 'Eileen "The Bold"',
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("Eileen \\"The Bold\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Eileen "The Bold"');
    });

    it("should escape backslash in display name (e.g. C:\\Path → C:\\\\Path)", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "C:\\Path",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("C:\\\\Path", color="#c8ffc8")'
      );
      expect(result).not.toContain("C:\\Path");
    });

    it("should escape both backslash and quote correctly when present together", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: 'Path\\To "File"',
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Both should be escaped: \ becomes \\, " becomes \"
      expect(result).toContain(
        'define e = Character("Path\\\\To \\"File\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Path\\To "File"');
    });

    it("should end with a newline when characters array is not empty", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Result should end with a newline
      expect(result.endsWith("\n")).toBe(true);
    });

    it("should append what_italic=True for narrator characters", () => {
      const characters = [
        {
          renpyTag: "n",
          displayName: "Narrator",
          color: "#cfcfcf",
          isNarrator: true,
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define n = Character("Narrator", color="#cfcfcf", what_italic=True)'
      );
    });

    it("should NOT append what_italic for non-narrator characters", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
          isNarrator: false,
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("Eileen", color="#c8ffc8")'
      );
      expect(result).not.toContain("what_italic");
    });

    it("should NOT append what_italic when isNarrator is omitted", () => {
      const characters = [
        {
          renpyTag: "s",
          displayName: "Sylvie",
          color: "#ff0000",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define s = Character("Sylvie", color="#ff0000")'
      );
      expect(result).not.toContain("what_italic");
    });

    it("should skip character with invalid renpyTag (e.g. with spaces or special chars)", () => {
      const characters = [
        {
          renpyTag: "valid_tag",
          displayName: "Valid",
          color: "#ffffff",
        },
        {
          renpyTag: "bad tag",
          displayName: "Bad Tag Character",
          color: "#ff0000",
        },
        {
          renpyTag: "ok",
          displayName: "Another Valid",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Valid characters should be included
      expect(result).toContain("valid_tag");
      expect(result).toContain("ok");
      // Invalid character should be skipped
      expect(result).not.toContain("bad tag");
      expect(result).not.toContain("Bad Tag Character");
    });

    it("should skip character with invalid color that is not a hex color", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
        {
          renpyTag: "h",
          displayName: "Hacker",
          color: 'red") $ evil = True #',
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Valid character should be included
      expect(result).toContain("define e = Character");
      expect(result).toContain("Eileen");
      // Malicious character should be skipped entirely
      expect(result).not.toContain("Hacker");
      expect(result).not.toContain("evil = True");
      expect(result).not.toContain('color="red');
    });

    it("should skip character with invalid renpyTag that starts with a digit", () => {
      const characters = [
        {
          renpyTag: "1bad",
          displayName: "StartsWithDigit",
          color: "#ffffff",
        },
        {
          renpyTag: "ok",
          displayName: "Valid",
          color: "#ffffff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).not.toContain("1bad");
      expect(result).toContain("ok");
    });

    it("should accept valid 6-digit hex colors", () => {
      const characters = [
        {
          renpyTag: "a",
          displayName: "White",
          color: "#ffffff",
        },
        {
          renpyTag: "b",
          displayName: "Red",
          color: "#ff0000",
        },
        {
          renpyTag: "c",
          displayName: "Blue",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define a = Character("White", color="#ffffff")'
      );
      expect(result).toContain('define b = Character("Red", color="#ff0000")');
      expect(result).toContain('define c = Character("Blue", color="#0000ff")');
    });
  });
});
