/**
 * RPY Generator Service Tests
 *
 * Unit tests for Ren'Py .rpy file generator.
 */

import { describe, it, expect } from "vitest";
import { generateCharacterDefinitionsFile } from "../rpy-generator.service.js";

describe("RPYGeneratorService", () => {
  describe("generateCharacterDefinitionsFile", () => {
    it("should return only the header with a trailing newline for empty characters array", () => {
      const result = generateCharacterDefinitionsFile([]);

      const expectedHeader = `##############################################################################
# Ren'Py Character Definitions
#
# This file was automatically generated by BranchForge
# Modifications may be overwritten during future exports
##############################################################################
`;

      expect(result).toBe(expectedHeader);
      expect(result.endsWith("\n")).toBe(true);
    });

    it("should generate correct define statement for single character", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain("# Ren'Py Character Definitions");
      expect(result).toContain("define e = Character");
    });

    it("should generate one define per character in order for multiple characters", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
        {
          renpyTag: "s",
          displayName: "Sylvie",
          color: "#ff0000",
        },
        {
          renpyTag: "l",
          displayName: "Lucy",
          color: "#0000ff",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        `define e = Character("Eileen", color="#c8ffc8")`
      );
      expect(result).toContain(
        `define s = Character("Sylvie", color="#ff0000")`
      );
      expect(result).toContain(`define l = Character("Lucy", color="#0000ff")`);

      // Check order: e should appear before s, s should appear before l
      const eIndex = result.indexOf('define e = Character("Eileen"');
      const sIndex = result.indexOf('define s = Character("Sylvie"');
      const lIndex = result.indexOf('define l = Character("Lucy"');

      expect(eIndex).toBeLessThan(sIndex);
      expect(sIndex).toBeLessThan(lIndex);
    });

    it('should escape double quotes in display name (e.g. Eileen "The Bold" → Eileen \\"The Bold\\")', () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: 'Eileen "The Bold"',
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("Eileen \\"The Bold\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Eileen "The Bold"');
    });

    it("should escape backslash in display name (e.g. C:\\Path → C:\\\\Path)", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "C:\\Path",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      expect(result).toContain(
        'define e = Character("C:\\\\Path", color="#c8ffc8")'
      );
      expect(result).not.toContain("C:\\Path");
    });

    it("should escape both backslash and quote correctly when present together", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: 'Path\\To "File"',
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Both should be escaped: \ becomes \\, " becomes \"
      expect(result).toContain(
        'define e = Character("Path\\\\To \\"File\\"", color="#c8ffc8")'
      );
      expect(result).not.toContain('Path\\To "File"');
    });

    it("should end with a newline when characters array is not empty", () => {
      const characters = [
        {
          renpyTag: "e",
          displayName: "Eileen",
          color: "#c8ffc8",
        },
      ];

      const result = generateCharacterDefinitionsFile(characters);

      // Result should end with a newline
      expect(result.endsWith("\n")).toBe(true);
    });
  });
});
